### ISSUE TITLE
Prevent workspace compilation error stem

### ISSUE THREAD

**Issue by xqft** [lambdaclass/ethrex#4507]
`alloy-consensus` <1.0.31 does not compile with serde >=1.0.220 due to a breaking change introduced in serde. A fixed was pushed to `alloy-consensus` for versions >=1.0.31 that fixes it. https://github.com/alloy-rs/alloy/pull/2875. `alloy-consensus` is a dependency of `revm`.

If we update our serde version (for example using `cargo update`) the workspace fails to compile because `ethrex-vm` and `ef_test` depend on revm. In particular `ethrex-vm` has it as an optional dependency, but for `ef_test` it's non-optional.

https://github.com/lambdaclass/ethrex/pull/4489 this PR fixes temporarily the problem by pinning serde version to one previous to the breaking change, but in the long term this may bring other issues. The ideal solution would be to update `revm`, but we could make `ef_tests` depend optionally on `revm` so that by default `revm` is not part of the workspace. Note that this would not solve the underlying problem if we would to enable the `revm` feature flag.
